name: Workflow
on:
  push:
    branches: [ main ]
    tags:
      - v**
  pull_request: { }

jobs:
  lint:
    strategy:
      matrix:
        pyversion: [ "3.11", "3.12" ]
    uses: BlindfoldedSurgery/actions-python/.github/workflows/lint.yml@v0
    with:
      python-version: ${{ matrix.pyversion }}

  test:
    strategy:
      matrix:
        pyversion: [ "3.11", "3.12" ]
    uses: BlindfoldedSurgery/actions-python/.github/workflows/test.yml@v0
    with:
      python-version: ${{ matrix.pyversion }}
      submit-coverage: ${{ matrix.pyversion == '3.11' }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish_package:
    runs-on: ubuntu-latest
    container: python:3.11-slim
    needs:
      - lint
      - test
    if: success() && startsWith(github.ref, 'refs/tags/v')
    env:
      POETRY_HTTP_BASIC_PYPI_BS_USERNAME: ${{ vars.PYPI_USERNAME }}
      POETRY_HTTP_BASIC_PYPI_BS_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
      - name: Install Poetry
        run: pip install poetry==1.6.1
      - uses: actions/checkout@v4
      - name: Build project
        run: poetry build
      - name: Upload to pypi registry
        run: poetry publish -r pypi-bs
