name: Workflow
on:
  push:
    branches: [ main ]
    tags:
      - v**
  pull_request: { }

jobs:
  lint:
    strategy:
      matrix:
        pyversion: [ "3.11", "3.12" ]
    uses: BlindfoldedSurgery/actions-python/.github/workflows/lint.yml@v0
    with:
      python-version: ${{ matrix.pyversion }}

  test:
    strategy:
      matrix:
        pyversion: [ "3.11", "3.12" ]
    uses: BlindfoldedSurgery/actions-python/.github/workflows/test.yml@v0
    with:
      python-version: ${{ matrix.pyversion }}
      submit-coverage: ${{ matrix.pyversion == '3.11' }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish_package:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/test.yml@v0
    needs:
      - lint
      - test
    if: success() && startsWith(github.ref, 'refs/tags/v')
    with:
      python-version: '3.11'
      pypi-username: ${{ vars.PYPI_USERNAME }}
    secrets:
      pypi-password: ${{ secrets.PYPI_PASSWORD }}
